/****** Object:  Database [RobertRouseVizBible]    Script Date: 12/19/2023 5:47:33 PM ******/
CREATE DATABASE [RobertRouseVizBible]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RobertRouseVizBible_Data', FILENAME = N'E:\SQLServerDataFiles\RobertRouseVizBible\RobertRouseVizBibleData.MDF' , SIZE = 8000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%) 
 LOG ON 
( NAME = N'RobertRouseVizBible_Log', FILENAME = N'E:\SQLServerDataFiles\RobertRouseVizBible\RobertRouseVizBibleLog.LDF' , SIZE = 8000KB , MAXSIZE = 2048GB , FILEGROWTH = 5%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [RobertRouseVizBible] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RobertRouseVizBible].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [RobertRouseVizBible] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET ARITHABORT OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RobertRouseVizBible] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RobertRouseVizBible] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RobertRouseVizBible] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RobertRouseVizBible] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET RECOVERY FULL 
GO
ALTER DATABASE [RobertRouseVizBible] SET  MULTI_USER 
GO
ALTER DATABASE [RobertRouseVizBible] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RobertRouseVizBible] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RobertRouseVizBible] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RobertRouseVizBible] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [RobertRouseVizBible] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RobertRouseVizBible] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [RobertRouseVizBible] SET QUERY_STORE = ON
GO
ALTER DATABASE [RobertRouseVizBible] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
