USE [master]
GO

/****** Object:  Database [Generative]    Script Date: 2/21/2014 9:40:19 PM ******/
CREATE DATABASE [Generative]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Generative_Data', FILENAME = N'E:\SQLServerDataFiles\Generative\GenerativeData.MDF' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
 FILEGROUP [Generative_Image_FileGroup] 
( NAME = N'Generative_Image', FILENAME = N'E:\SQLServerDataFiles\Generative\GenerativeImage.NDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [Generative_Index_FileGroup] 
( NAME = N'Generative_Index', FILENAME = N'E:\SQLServerDataFiles\Generative\GenerativeIndex.NDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
 FILEGROUP [Generative_Text_FileGroup] 
( NAME = N'Generative_Text', FILENAME = N'E:\SQLServerDataFiles\Generative\GenerativeText.NDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
 FILEGROUP [Generative_Xml_FileGroup] 
( NAME = N'Generative_Xml', FILENAME = N'E:\SQLServerDataFiles\Generative\GenerativeXml.NDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%)
 LOG ON 
( NAME = N'Generative_Log', FILENAME = N'E:\SQLServerDataFiles\Generative\GenerativeLog.LDF' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 5%)
GO

ALTER DATABASE [Generative] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Generative].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Generative] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Generative] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Generative] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Generative] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Generative] SET ARITHABORT OFF 
GO

ALTER DATABASE [Generative] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Generative] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Generative] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Generative] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Generative] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Generative] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Generative] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Generative] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Generative] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Generative] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Generative] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Generative] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Generative] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Generative] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Generative] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Generative] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Generative] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Generative] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Generative] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Generative] SET  MULTI_USER 
GO

ALTER DATABASE [Generative] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Generative] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Generative] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Generative] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Generative] SET  READ_WRITE 
GO

