USE [master]
GO

/****** Object:  Database [SQLSharp]    Script Date: 4/22/2020 3:09:30 PM ******/
CREATE DATABASE [SQLSharp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SQLSharp_Data', FILENAME = N'E:\SQLServerDataFiles\SQLSharp\SQLSharpData.MDF' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
 FILEGROUP [SQLSharp_Image_FileGroup] 
( NAME = N'SQLSharp_Image', FILENAME = N'E:\SQLServerDataFiles\SQLSharp\SQLSharpImage.NDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [SQLSharp_Index_FileGroup] 
( NAME = N'SQLSharp_Index', FILENAME = N'E:\SQLServerDataFiles\SQLSharp\SQLSharpIndex.NDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
 FILEGROUP [SQLSharp_Text_FileGroup] 
( NAME = N'SQLSharp_Text', FILENAME = N'E:\SQLServerDataFiles\SQLSharp\SQLSharpText.NDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
 FILEGROUP [SQLSharp_Xml_FileGroup] 
( NAME = N'SQLSharp_Xml', FILENAME = N'E:\SQLServerDataFiles\SQLSharp\SQLSharpXml.NDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%)
 LOG ON 
( NAME = N'SQLSharp_Log', FILENAME = N'E:\SQLServerDataFiles\SQLSharp\SQLSharpLog.LDF' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 5%)
GO

ALTER DATABASE [SQLSharp] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SQLSharp].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [SQLSharp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SQLSharp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SQLSharp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SQLSharp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SQLSharp] SET ARITHABORT OFF 
GO

ALTER DATABASE [SQLSharp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SQLSharp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SQLSharp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SQLSharp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SQLSharp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SQLSharp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SQLSharp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SQLSharp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SQLSharp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SQLSharp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SQLSharp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SQLSharp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SQLSharp] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [SQLSharp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SQLSharp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SQLSharp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SQLSharp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SQLSharp] SET RECOVERY FULL 
GO

ALTER DATABASE [SQLSharp] SET  MULTI_USER 
GO

ALTER DATABASE [SQLSharp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SQLSharp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SQLSharp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SQLSharp] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SQLSharp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SQLSharp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SQLSharp] SET  READ_WRITE 
GO


