CREATE DATABASE [UserDb] ON  PRIMARY 
( NAME = N'UserDb_Data', FILENAME = N'E:\SQLServerDataFiles\UserDb\UserDbData.MDF' , SIZE = 2028KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
 FILEGROUP [UserDb_Image_FileGroup] 
( NAME = N'UserDb_Image', FILENAME = N'E:\SQLServerDataFiles\UserDb\UserDbImage.NDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
 FILEGROUP [UserDb_Index_FileGroup] 
( NAME = N'UserDb_Index', FILENAME = N'E:\SQLServerDataFiles\UserDb\UserDbIndex.NDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
 FILEGROUP [UserDb_Text_FileGroup] 
( NAME = N'UserDb_Text', FILENAME = N'E:\SQLServerDataFiles\UserDb\UserDbText.NDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
 FILEGROUP [UserDb_Xml_FileGroup] 
( NAME = N'UserDb_Xml', FILENAME = N'E:\SQLServerDataFiles\UserDb\UserDbXml.NDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%)
 LOG ON 
( NAME = N'UserDb_Log', FILENAME = N'E:\SQLServerDataFiles\UserDb\UserDbLog.LDF' , SIZE = 1024KB, MAXSIZE = 2048GB , FILEGROWTH = 5%)
GO

EXEC sp_dboption UserDB, 'trunc. log on chkpt.', 'true'
GO

ALTER DATABASE UserDb SET RECOVERY SIMPLE
GO

ALTER DATABASE [UserDb] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UserDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UserDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UserDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UserDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UserDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [UserDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UserDb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [UserDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UserDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UserDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UserDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UserDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UserDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UserDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UserDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UserDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UserDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UserDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UserDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UserDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UserDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UserDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UserDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UserDb] SET  READ_WRITE 
GO

ALTER DATABASE [UserDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UserDb] SET  MULTI_USER 
GO

ALTER DATABASE [UserDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UserDb] SET DB_CHAINING OFF 
GO

USE [UserDb]
GO

CREATE TABLE [dbo].[UserUnique](
	[UserUniqueId] [int] IDENTITY(1,1) NOT NULL,
	[Dated] [datetime] NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[FavoriteColor] [varchar](20) NOT NULL,
	CONSTRAINT [PK_UserUnique] PRIMARY KEY CLUSTERED 
(
	[UserName] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[UserUnique] ADD  CONSTRAINT [DF_UserUnique_Dated]  DEFAULT (getdate()) FOR [Dated]
GO
